Add tox.ini.
Note that one test on Plone 4.3 fails:

```
Failure in test testRenderTiles (plone.app.blocks.tests.test_tiles.TestRenderTiles)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/maurits/clients/zeelandia/plone52/develop/plone.app.blocks/plone/app/blocks/tests/test_tiles.py", line 236, in testRenderTiles
    self.assertIn(u'Umlauts: \xdcbertile', result)
  File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/unittest/case.py", line 804, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: u'Umlauts: \xdcbertile' not found in u'<!DOCTYPE html>\n<html data-layout="./@@default-site-layout">\n<head><meta name="tile-name" content="tile2">\n<meta name="tile-name" content="tile3">\n<meta name="tile-name" content="tile4">\n</head>\n<body>\n  <h1>Welcome!</h1>\n  <div data-panel="panel1">\n    Page panel 1\n    \n  <p>\n    This is a demo tile with id tile2\n  </p>\n  <p>\n    Magic number: 2; Form: [(\'magicNumber\', 2)];\n    Query string: magicNumber:int=2; URL: http://nohost/@@test.tile1/tile2\n    Umlauts: \xc3\x9cbertile ;)\n  </p>\n\n  </div>\n  <div data-panel="panel2">\n    Page panel 2\n    \n  <p>\n    This is a demo tile with id tile3\n  </p>\n  <p>\n    Magic number: -1; Form: [];\n    Query string: ; URL: http://nohost/@@test.tile1/tile3\n    Umlauts: \xc3\x9cbertile ;)\n  </p>\n\n  </div>\n  <div data-panel="panel4">\n    Page panel 4 (ignored)\n    \n  <p>\n    This is a demo tile with id tile4\n  </p>\n  <p>\n    Magic number: -1; Form: [];\n    Query string: ; URL: http://nohost/@@test.tile1/tile4\n    Umlauts: \xc3\x9cbertile ;)\n  </p>\n\n  </div>\n</body>\n</html>'
```

So we expect this:

```
>>> print(u"Umlauts: \xdcbertile")
Umlauts: Übertile
```

But we get this:

```
>>> print(u"Umlauts: \xc3\x9cbertile")
Umlauts: Ãbertile
```

This is close, but not correct.